name: tests
on:
  push:
    branches: [ main ]
jobs:
  test-modules:
   runs-on: ubuntu-latest
   strategy:
      matrix:
        node-version: [14.x]
   steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}  
      - run: make install
      - run: make lint
      - run: make test
      - name: publish code coverage
        uses: paambaati/codeclimate-action@v2.5.7
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CODECLIMATE_SECRET}}
        with:
          coverageCommand:  make coverage-tests
          debug: true
